// Lee, Jeongeun, 20215747
// Haddad, Sara, 20208373
  
var tarteExiste = false;

const names = ["Red",
				"Maroon",
				"Scarlet",
				"Brick Red",
				"English Vermilion",
				"Madder Lake",
				"Permanent Geranium Lake",
				"Maximum Red",
				"Indian Red",
				"Orange-Red",
				"Sunset Orange",
				"Bittersweet",
				"Dark Venetian Red",
				"Venetian Red",
				"Light Venetian Red",
				"Vivid Tangerine",
				"Middle Red",
				"Burnt Orange",
				"Red-Orange",
				"Orange",
				"Macaroni and Cheese",
				"Middle Yellow Red",
				"Mango Tango",
				"Yellow-Orange",
				"Maximum Yellow Red",
				"Banana Mania",
				"Maize",
				"Orange-Yellow",
				"Goldenrod",
				"Dandelion",
				"Yellow",
				"Green-Yellow",
				"Middle Yellow",
				"Olive Green",
				"Spring Green",
				"Maximum Yellow",
				"Canary",
				"Lemon Yellow",
				"Maximum Green Yellow",
				"Middle Green Yellow",
				"Inchworm",
				"Light Chrome Green",
				"Yellow-Green",
				"Maximum Green",
				"Asparagus",
				"Granny Smith Apple",
				"Fern",
				"Middle Green",
				"Green",
				"Medium Chrome Green",
				"Forest Green",
				"Sea Green",
				"Shamrock",
				"Mountain Meadow",
				"Jungle Green",
				"Caribbean Green",
				"Tropical Rain Forest",
				"Middle Blue Green",
				"Pine Green",
				"Maximum Blue Green",
				"Robin's Egg Blue",
				"Teal Blue",
				"Light Blue",
				"Aquamarine",
				"Turquoise Blue",
				"Outer Space",
				"Sky Blue",
				"Middle Blue",
				"Blue-Green",
				"Pacific Blue",
				"Cerulean",
				"Maximum Blue",
				"Blue (I)",
				"Cerulean Blue",
				"Cornflower",
				"Green-Blue",
				"Midnight Blue",
				"Navy Blue",
				"Denim",
				"Blue (III)",
				"Cadet Blue",
				"Periwinkle",
				"Blue (II)",
				"Wild Blue Yonder",
				"Indigo",
				"Manatee",
				"Cobalt Blue",
				"Celestial Blue",
				"Blue Bell",
				"Maximum Blue Purple",
				"Violet-Blue",
				"Blue-Violet",
				"Ultramarine Blue",
				"Middle Blue Purple",
				"Purple Heart",
				"Royal Purple",
				"Violet (II)",
				"Medium Violet",
				"Wisteria",
				"Lavender (I)",
				"Vivid Violet",
				"Maximum Purple",
				"Purple Mountains' Majesty",
				"Fuchsia",
				"Pink Flamingo",
				"Violet (I)",
				"Brilliant Rose",
				"Orchid",
				"Plum",
				"Medium Rose",
				"Thistle",
				"Mulberry",
				"Red-Violet",
				"Middle Purple",
				"Maximum Red Purple",
				"Jazzberry Jam",
				"Eggplant",
				"Magenta",
				"Cerise",
				"Wild Strawberry",
				"Lavender (II)",
				"Cotton Candy",
				"Carnation Pink",
				"Violet-Red",
				"Razzmatazz",
				"Pig Pink",
				"Carmine",
				"Blush",
				"Tickle Me Pink",
				"Mauvelous",
				"Salmon",
				"Middle Red Purple",
				"Mahogany",
				"Melon",
				"Pink Sherbert",
				"Burnt Sienna",
				"Brown",
				"Sepia",
				"Fuzzy Wuzzy",
				"Beaver",
				"Tumbleweed",
				"Raw Sienna",
				"Van Dyke Brown",
				"Tan",
				"Desert Sand",
				"Peach",
				"Burnt Umber",
				"Apricot",
				"Almond",
				"Raw Umber",
				"Shadow",
				"Raw Sienna (I)",
				"Timberwolf",
				"Gold (I)",
				"Gold (II)",
				"Silver",
				"Copper",
				"Antique Brass",
				"Black",
				"Charcoal Gray",
				"Gray",
				"Blue-Gray",
				"Radical Red",
				"Wild Watermelon",
				"Outrageous Orange",
				"Atomic Tangerine",
				"Neon Carrot",
				"Sunglow",
				"Laser Lemon",
				"Unmellow Yellow",
				"Electric Lime",
				"Screamin' Green",
				"Magic Mint",
				"Blizzard Blue",
				"Shocking Pink",
				"Razzle Dazzle Rose",
				"Hot Magenta",
				"Purple Pizzazz",
				"Sizzling Red",
				"Red Salsa",
				"Tart Orange",
				"Orange Soda",
				"Bright Yellow",
				"Yellow Sunshine",
				"Slimy Green",
				"Green Lizard",
				"Denim Blue",
				"Blue Jeans",
				"Plump Purple",
				"Purple Plum",
				"Sweet Brown",
				"Brown Sugar",
				"Eerie Black",
				"Black Shadows",
				"Fiery Rose",
				"Sizzling Sunrise",
				"Heat Wave",
				"Lemon Glacier",
				"Spring Frost",
				"Absolute Zero",
				"Winter Sky",
				"Frostbite",
				"Alloy Orange",
				"B'dazzled Blue",
				"Big Dip O' Ruby",
				"Bittersweet Shimmer",
				"Blast Off Bronze",
				"Cyber Grape",
				"Deep Space Sparkle",
				"Gold Fusion",
				"Illuminating Emerald",
				"Metallic Seaweed",
				"Metallic Sunburst",
				"Razzmic Berry",
				"Sheen Green",
				"Shimmering Blush",
				"Sonic Silver",
				"Steel Blue",
				"Aztec Gold",
				"Burnished Brown",
				"Cerulean Frost",
				"Cinnamon Satin",
				"Copper Penny",
				"Cosmic Cobalt",
				"Glossy Grape",
				"Granite Gray",
				"Green Sheen",
				"Lilac Luster",
				"Misty Moss",
				"Mystic Maroon",
				"Pearly Purple",
				"Pewter Blue",
				"Polished Pine",
				"Quick Silver",
				"Rose Dust",
				"Rusty Red",
				"Shadow Blue",
				"Shiny Shamrock",
				"Steel Teal",
				"Sugar Plum",
				"Twilight Lavender",
				"Wintergreen Dream",
				"Baby Powder",
				"Banana",
				"Blueberry",
				"Bubble Gum",
				"Cedar Chest",
				"Cherry",
				"Chocolate",
				"Coconut",
				"Daffodil",
				"Dirt",
				"Eucalyptus",
				"Fresh Air",
				"Grape",
				"Jelly Bean",
				"Leather Jacket",
				"Lemon",
				"Licorice",
				"Lilac",
				"Lime",
				"Lumber",
				"New Car",
				"Orange",
				"Peach",
				"Pine",
				"Rose",
				"Shampoo",
				"Smoke",
				"Soap",
				"Strawberry",
				"Tulip",
				"Amethyst",
				"Citrine",
				"Emerald",
				"Jade",
				"Jasper",
				"Lapis Lazuli",
				"Malachite",
				"Moonstone",
				"Onyx",
				"Peridot",
				"Pink Pearl",
				"Rose Quartz",
				"Ruby",
				"Sapphire",
				"Smokey Topaz",
				"Tiger's Eye",
				"Baseball Mitt (Burnt Sienna)",
				"Bubble Bath (Tickle Me Pink)",
				"Earthworm (Brick Red)",
				"Flower Shop (Wisteria)",
				"Fresh Air (Sky Blue)",
				"Grandma's Perfume (Orange)",
				"Koala Tree (Jungle Green)",
				"Pet Shop (Brown)",
				"Pine Tree (Pine Green)",
				"Saw Dust (Peach)",
				"Sharpening Pencils (Goldenrod)",
				"Smell the Roses (Red)",
				"Sunny Day (Yellow)",
				"Wash the Dog (Dandelion)",
				"Alien Armpit",
				"Big Foot Feet",
				"Booger Buster",
				"Dingy Dungeon",
				"Gargoyle Gas",
				"Giant's Club",
				"Magic Potion",
				"Mummy's Tomb",
				"Ogre Odor",
				"Pixie Powder",
				"Princess Perfume",
				"Sasquatch Socks",
				"Sea Serpent",
				"Smashed Pumpkin",
				"Sunburnt Cyclops",
				"Winter Wizard"];

const colors = ["#ED0A3F",
				"#C32148",
				"#FD0E35",
				"#C62D42",
				"#CC474B",
				"#CC3336",
				"#E12C2C",
				"#D92121",
				"#B94E48",
				"#FF5349",
				"#FE4C40",
				"#FE6F5E",
				"#B33B24",
				"#CC553D",
				"#E6735C",
				"#FF9980",
				"#E58E73",
				"#FF7F49",
				"#FF681F",
				"#FF8833",
				"#FFB97B",
				"#ECAC76",
				"#E77200",
				"#FFAE42",
				"#F2BA49",
				"#FBE7B2",
				"#F2C649",
				"#F8D568",
				"#FCD667",
				"#FED85D",
				"#FBE870",
				"#F1E788",
				"#FFEB00",
				"#B5B35C",
				"#ECEBBD",
				"#FAFA37",
				"#FFFF99",
				"#FFFF9F",
				"#D9E650",
				"#ACBF60",
				"#AFE313",
				"#BEE64B",
				"#C5E17A",
				"#5E8C31",
				"#7BA05B",
				"#9DE093",
				"#63B76C",
				"#4D8C57",
				"#3AA655",
				"#6CA67C",
				"#5FA777",
				"#93DFB8",
				"#33CC99",
				"#1AB385",
				"#29AB87",
				"#00CC99",
				"#00755E",
				"#8DD9CC",
				"#01786F",
				"#30BFBF",
				"#00CCCC",
				"#008080",
				"#8FD8D8",
				"#95E0E8",
				"#6CDAE7",
				"#2D383A",
				"#76D7EA",
				"#7ED4E6",
				"#0095B7",
				"#009DC4",
				"#02A4D3",
				"#47ABCC",
				"#2EB4E6",
				"#339ACC",
				"#93CCEA",
				"#2887C8",
				"#00468C",
				"#0066CC",
				"#1560BD",
				"#0066FF",
				"#A9B2C3",
				"#C3CDE6",
				"#4570E6",
				"#7A89B8",
				"#4F69C6",
				"#8D90A1",
				"#8C90C8",
				"#7070CC",
				"#9999CC",
				"#ACACE6",
				"#766EC8",
				"#6456B7",
				"#3F26BF",
				"#8B72BE",
				"#652DC1",
				"#6B3FA0",
				"#8359A3",
				"#8F47B3",
				"#C9A0DC",
				"#BF8FCC",
				"#803790",
				"#733380",
				"#D6AEDD",
				"#C154C1",
				"#FC74FD",
				"#732E6C",
				"#E667CE",
				"#E29CD2",
				"#8E3179",
				"#D96CBE",
				"#EBB0D7",
				"#C8509B",
				"#BB3385",
				"#D982B5",
				"#A63A79",
				"#A50B5E",
				"#614051",
				"#F653A6",
				"#DA3287",
				"#FF3399",
				"#FBAED2",
				"#FFB7D5",
				"#FFA6C9",
				"#F7468A",
				"#E30B5C",
				"#FDD7E4",
				"#E62E6B",
				"#DB5079",
				"#FC80A5",
				"#F091A9",
				"#FF91A4",
				"#A55353",
				"#CA3435",
				"#FEBAAD",
				"#F7A38E",
				"#E97451",
				"#AF593E",
				"#9E5B40",
				"#87421F",
				"#926F5B",
				"#DEA681",
				"#D27D46",
				"#664228",
				"#D99A6C",
				"#EDC9AF",
				"#FFCBA4",
				"#805533",
				"#FDD5B1",
				"#EED9C4",
				"#665233",
				"#837050",
				"#E6BC5C",
				"#D9D6CF",
				"#92926E",
				"#E6BE8A",
				"#C9C0BB",
				"#DA8A67",
				"#C88A65",
				"#000000",
				"#736A62",
				"#8B8680",
				"#C8C8CD",
				"#FF355E",
				"#FD5B78",
				"#FF6037",
				"#FF9966",
				"#FF9933",
				"#FFCC33",
				"#FFFF66",
				"#FFFF66",
				"#CCFF00",
				"#66FF66",
				"#AAF0D1",
				"#50BFE6",
				"#FF6EFF",
				"#EE34D2",
				"#FF00CC",
				"#FF00CC",
				"#FF3855",
				"#FD3A4A",
				"#FB4D46",
				"#FA5B3D",
				"#FFAA1D",
				"#FFF700",
				"#299617",
				"#A7F432",
				"#2243B6",
				"#5DADEC",
				"#5946B2",
				"#9C51B6",
				"#A83731",
				"#AF6E4D",
				"#1B1B1B",
				"#BFAFB2",
				"#FF5470",
				"#FFDB00",
				"#FF7A00",
				"#FDFF00",
				"#87FF2A",
				"#0048BA",
				"#FF007C",
				"#E936A7",
				"#c46210",
				"#2e5894",
				"#9c2542",
				"#bf4f51",
				"#a57164",
				"#58427c",
				"#4a646c",
				"#85754e",
				"#319177",
				"#0a7e8c",
				"#9c7c38",
				"#8d4e85",
				"#8fd400",
				"#d98695",
				"#757575",
				"#0081ab",
				"#C39953",
				"#A17A74",
				"#6D9BC3",
				"#CD607E",
				"#AD6F69",
				"#2E2D88",
				"#AB92B3",
				"#676767",
				"#6EAEA1",
				"#AE98AA",
				"#BBB477",
				"#AD4379",
				"#B768A2",
				"#8BA8B7",
				"#5DA493",
				"#A6A6A6",
				"#9E5E6F",
				"#DA2C43",
				"#778BA5",
				"#5FA778",
				"#5F8A8B",
				"#914E75",
				"#8A496B",
				"#56887D",
				"#FEFEFA",
				"#FFD12A",
				"#4F86F7",
				"#FFD3F8",
				"#C95A49",
				"#DA2647",
				"#BD8260",
				"#FEFEFE",
				"#FFFF31",
				"#9B7653",
				"#44D7A8",
				"#A6E7FF",
				"#6F2DA8",
				"#DA614E",
				"#253529",
				"#FFFF38",
				"#1A1110",
				"#DB91EF",
				"#B2F302",
				"#FFE4CD",
				"#214FC6",
				"#FF8866",
				"#FFD0B9",
				"#45A27D",
				"#FF5050",
				"#FFCFF1",
				"#738276",
				"#CEC8EF",
				"#FC5A8D",
				"#FF878D",
				"#64609A",
				"#933709",
				"#14A989",
				"#469A84",
				"#D05340",
				"#436CB9",
				"#469496",
				"#3AA8C1",
				"#353839",
				"#ABAD48",
				"#B07080",
				"#BD559C",
				"#AA4069",
				"#2D5DA1",
				"#832A0D",
				"#B56917",
				"#E97451",
				"#FC80A5",
				"#C62D42",
				"#C9A0DC",
				"#76D7EA",
				"#FF8833",
				"#29AB87",
				"#AF593E",
				"#01786F",
				"#FFCBA4",
				"#FCD667",
				"#ED0A3F",
				"#FBE870",
				"#FED85D",
				"#84DE02",
				"#E88E5A",
				"#DDE26A",
				"#C53151",
				"#FFDF46",
				"#B05C52",
				"#FF4466",
				"#828E84",
				"#FD5240",
				"#391285",
				"#FF85CF",
				"#FF4681",
				"#4BC7CF",
				"#FF6D3A",
				"#FF404C",
				"#A0E6FF"];

$(document).ready(function() {
	loadImage();

	$("#lancer").click(function(){
		loadImage();
	});
});


function loadImage(){
	$("#display").attr('src', $("#imageURL").val());
	var img = new Image();
	img.crossOrigin = 'anonymous';
	img.src = $("#imageURL").val();

	var canvas = document.getElementById('canvas');
	var ctx = canvas.getContext('2d');

	var numSamplePixels = 100;
	canvas.setAttribute("width", Math.floor(Math.sqrt(numSamplePixels)));
	canvas.setAttribute("height", Math.floor(Math.sqrt(numSamplePixels)));

	ctx.clearRect(0, 0, canvas.width, canvas.height);

	img.onload = function(){
		var hRatio = canvas.width / img.width;
		var vRatio = canvas.height / img.height;

		var ratio  = Math.min(hRatio, vRatio);

		ctx.drawImage(img, 0, 0, img.width, img.height, 0, 0, img.width*ratio, img.height*ratio);

		var data = ctx.getImageData(0, 0, img.width*ratio, img.height*ratio).data;
		createPie(data);
	};


}

function getDistance(lab1, lab2){
	result = Math.pow(lab1[0] - lab2[0], 2);
	result += Math.pow(lab1[1] - lab2[1], 2);
	result += Math.pow(lab1[2] - lab2[2], 2);

	return Math.sqrt(result);
}

function rgb2lab(rgb){
	var r = rgb[0] / 255,
		g = rgb[1] / 255,
		b = rgb[2] / 255,
		x, y, z;

	r = (r > 0.04045) ? Math.pow((r + 0.055) / 1.055, 2.4) : r / 12.92;
	g = (g > 0.04045) ? Math.pow((g + 0.055) / 1.055, 2.4) : g / 12.92;
	b = (b > 0.04045) ? Math.pow((b + 0.055) / 1.055, 2.4) : b / 12.92;

	x = (r * 0.4124 + g * 0.3576 + b * 0.1805) / 0.95047;
	y = (r * 0.2126 + g * 0.7152 + b * 0.0722) / 1.00000;
	z = (r * 0.0193 + g * 0.1192 + b * 0.9505) / 1.08883;

	x = (x > 0.008856) ? Math.pow(x, 1/3) : (7.787 * x) + 16/116;
	y = (y > 0.008856) ? Math.pow(y, 1/3) : (7.787 * y) + 16/116;
	z = (z > 0.008856) ? Math.pow(z, 1/3) : (7.787 * z) + 16/116;

	return [(116 * y) - 16, 500 * (x - y), 200 * (y - z)]
}

function hex2rgb(hex) {
	var result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
	return [parseInt(result[1], 16), parseInt(result[2], 16), parseInt(result[3], 16)];
}

// Prend en entree un tableau [r, g, b] 
// et retourne l'index de la couleur la plus
// proche dans le tableau colors
function getClosestColor(rgb){
	minimum = 195075;
	index = -1;

	for(var i = 0; i < colors.length; i++){
		var distance = getDistance(rgb2lab(hex2rgb(colors[i])), rgb2lab(rgb));

		if(distance < minimum){
			minimum = distance;
			index = i;
		}
	}

	return index;
}
// Cette fonction permet de creer le beigne en fonction des couleurs, de leurs presence dans
// la photo et de leurs frequences
function createPie(data){
	if(tarteExiste){               // verifier qu'on a efface la tarte cree avant et que la page est vide
		window.myChart.destroy()   // detruire la tarte existante quand on change de photos
	}
    var frequences = Array(colors.length);   // nous allons mettre a jour ce tableau en fonction des couleurs de la photo

    for(var i=0 ; i<colors.length; i++){     // remplir le tableau par des 0 pour pouvoir incrementer
        frequences[i] =0;   
    }

    for(var i=0 ; i<data.length; i+=4){
        var tmp = [];
        for(var j=i; j < i + 3; j++) {       // mettre les valeurs en rouge, bleu et vert dans un nouveau tableaux en excluant la transparence
            tmp.push(data[j]);
        }
        var index = getClosestColor(tmp);    // voir la couleur la plus proche des valeurs du tableau

        frequences[index]++;
    }

    var labels = [];
    var datalist = [];
    var backgroundColors = [];
    for(var i=0; i < frequences.length; i++) {
        if(frequences[i] > 0) {             // la couleur est presente dans la photo
            labels.push(names[i]);          // ajout du nom et de la couleur 
            datalist.push(frequences[i]);
            bgcolor = hex2rgb(colors[i]);   // convertir en rgb
  
            var tmp = 'rgb(';               // avoir le format correct
            tmp += bgcolor.join() + ')';
            backgroundColors.push(tmp);
        }

    }
    // on creee notre chart
    var ctx = document.getElementById('pie-chart');
    window.myChart = new Chart(ctx, {
        type: 'doughnut',
        data: {
            labels: labels,
            datasets: [{
                label: 'My First Dataset',
                data: datalist,
                backgroundColor: backgroundColors,
                hoverOffset: 4
            }]
        }});
		tarteExiste=true   // on a dessine une tarte
}